- Makefile
- README.md
- example/README.md
- example/lib/main.dart
- example/pubspec.yaml
- packages/bugsnag_flutter/pubspec.yaml
Added a `publish` target that creates `/staging` directory with the correct structure and content for publishing to pub.dev.
Also added/tidied some content, such as details in pubspec.yml and added a build badge to the readme.
This passes the validation you get when you run `dart pub publish --dry-run`.
> build: add publish step for pub-dev staging

- Makefile
Remove IDE generated directories from `example` during a `clean` so that the staged Example app accurately reflects what can be published.
We should always publish from a clean checkout of the repository or (preferably) from a CI instance, but this adds an additional layer of safety.
Manual testing
> Remove IDE / user directories during clean

- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/test/bugsnag_test.dart
Improve the detection of `projectPackages` so that packages containing the word `bugsnag` are not accidentally seen as "Bugsnag" stack frames.
A new unit test was added
> Improve default projectPackages detection

- .buildkite/pipeline.yml
Check our assumption that `Frameworks/App.framework/App`'s UUID changes when Dart code changes, since we use that as the `codeIdentifier` to uniquely identify each build.
Rebuilds example app after changing one of the source files and checks that UUID changes.
Tested on CI.
> [PLAT-8425] Verify that UUID / codeIdentifier changes

- features/detect_enabled_errors.feature
- features/fixtures/app/lib/scenarios/detect_enabled_errors.dart
- features/fixtures/app/lib/scenarios/scenarios.dart
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/config.dart
Distinguish unhandled exceptions that happen on the JVM/Android Runtime (on Android) and those that happen in Dart.
New end to end test scenario
> Split `unhandledExceptions` into Java and Dart errors

- packages/bugsnag_flutter/lib/src/model/app.dart
`App.codeBundleId` is only applicable to ReactNative applications (which the Flutter layer cannot receive or process events from as things stand). This PR removes that field.
Relied on existing tests.
> Remove ReactNative-specific `codeBundleId` from App

- example/lib/main.dart
- features/fixtures/app/lib/scenarios/project_packages_scenario.dart
- features/project_packages.feature
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/config.dart
- packages/bugsnag_flutter/test/bugsnag_test.dart
Provide a more flexible way of specifying `projectPackages` using a custom wrapper type.
In order to allow for `projectPackages` to be declared in Dart but still possibly include platform-specific packages (currently just the Android application package) we add a new `ProjectPackages` class similar to the existing `EnabledErrorTypes` and `EndpointConfiguration`.
The new class also takes care of the Dart package-detection when no `projectPackages` are specified in `Bugsnag.start`.
Modified existing unit test and end2end scenario
> Use a more flexible `ProjectPackages` type

- packages/bugsnag_flutter/lib/src/config.dart
`ProjectPackages.withPlatformDefaults` should have been `const` as it has a fixed compile-time value.
No testing required
> `withPlatformDefaults` should be `const`

- features/fixtures/app/lib/scenarios/on_error_scenario.dart
- features/fixtures/app/lib/scenarios/scenarios.dart
- features/on_error.feature
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
Fix unsymbolicated stack frames on iOS when an `onError:` callback is configured.
Symbolicates stack frames before serializing to JSON.
Adds an E2E scenario that replicated the issue and verifies the fix.
> Fix iOS symbolication in presence of onError

- features/fixtures/app/lib/scenarios/project_packages_scenario.dart
- features/project_packages.feature
- packages/bugsnag_flutter/lib/bugsnag.dart
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/config.dart
- packages/bugsnag_flutter/test/bugsnag_test.dart
- packages/bugsnag_flutter/test/project_packages_test.dart
Remove the confusing `withPlatformDefaults` and introduce a simpler `ProjectPackages.withDefaults` which includes the default Android & Dart packages.
New unit tests to cover `ProjectPackages`
> Replace `ProjectPackages.withPlatformDefaults` with `withDefaults`

- features/fixtures/app/lib/scenarios/last_run_info_scenario.dart
- features/fixtures/app/lib/scenarios/on_error_scenario.dart
- features/fixtures/app/lib/scenarios/start_bugsnag_scenario.dart
- features/on_error.feature
- packages/bugsnag_flutter/lib/bugsnag_flutter.dart
- packages/bugsnag_flutter/lib/src/bugsnag_stacktrace.dart
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/model/event.dart
- packages/bugsnag_flutter/lib/src/model/session.dart
- packages/bugsnag_flutter/lib/src/model/user.dart
- packages/bugsnag_flutter/test/bugsnag_stacktrace_test.dart
- packages/bugsnag_flutter/test/channel_client_test.dart
- packages/bugsnag_flutter/test/error_factory_test.dart
- packages/bugsnag_flutter/test/model/app_test.dart
- packages/bugsnag_flutter/test/model/breadcrumbs_test.dart
- packages/bugsnag_flutter/test/model/device_test.dart
- packages/bugsnag_flutter/test/model/error_test.dart
- packages/bugsnag_flutter/test/model/event_test.dart
- packages/bugsnag_flutter/test/model/metadata_test.dart
- packages/bugsnag_flutter/test/model/stackframe_test.dart
- packages/bugsnag_flutter/test/model/thread_test.dart
- packages/bugsnag_flutter/test/model/user_test.dart
Prevent exporting class names that are likely to clash with application code - e.g. `App`, `Device`, `User`.
Exports fewer classes from `bugsnag_flutter.dart` and renames `User` to `BugsnagUser`.
Updates `OnErrorScenario` to ensure that `app` and `device` can still be accessed & manipulated.
> [PLAT-8521] Avoid name clashes

- packages/bugsnag_flutter/lib/src/client.dart
Fix the following compiler and lint warning:
```
: Warning: Operand of null-aware operation '?.' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart'
final lifecycleState = SchedulerBinding.instance?.lifecycleState.toString();
^
```
Casts `SchedulerBinding.instance` to `SchedulerBinding?` because `// ignore: invalid_null_aware_operator` doesn't silence the compiler warning 🤷
Supersedes #125
Verified locally with
```
Flutter 3.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision ee4e09cce0 (3 weeks ago) • 2022-05-09 16:45:18 -0700
Engine • revision d1b9a6938a
Tools • Dart 2.17.0 • DevTools 2.12.2
```
> Fix invalid null aware operator compiler warning

- .buildkite/pipeline.yml
- Makefile
- features/scripts/build_android_app.sh
- features/scripts/build_ios_app.sh
Add support for multiple version of Flutter within the CI pipeline.
`Makefile` and build scripts have been updated to allow for multiple versions of Flutter while allowing for normal operation on local machines.
Full CI has been run
> Add multiple versions of Flutter to the CI pipeline

- .buildkite/pipeline.yml
- example/android/app/build.gradle
- example/android/app/src/main/AndroidManifest.xml
- example/pubspec.yaml
- features/fixtures/app/android/app/build.gradle
- features/fixtures/app/android/app/src/main/AndroidManifest.xml
- features/fixtures/app/android/app/src/main/java/com/bugsnag/flutter/test/app/MazeRunnerMethodCallHandler.java
- features/fixtures/app/lib/scenarios/scenarios.dart
- features/fixtures/app/pubspec.lock
- features/fixtures/app/pubspec.yaml
- packages/bugsnag_flutter/lib/src/bugsnag_stacktrace.dart
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/enum_utils.dart
- packages/bugsnag_flutter/lib/src/model/breadcrumbs.dart
- packages/bugsnag_flutter/lib/src/model/event.dart
- packages/bugsnag_flutter/lib/src/model/stackframe.dart
- packages/bugsnag_flutter/lib/src/model/thread.dart
- packages/bugsnag_flutter/pubspec.yaml
Allow the core `bugsnag_flutter` library to be used with Flutter 2.5.0 and higher.
Relied on existing tests running under Flutter 2.5.0
> Port to Flutter 2.5.0

- packages/bugsnag_breadcrumbs_dart_io/pubspec.yaml
- packages/bugsnag_breadcrumbs_http/pubspec.yaml
Allow `bugsnag_breadcrumbs_dart_io` and `bugsnag_breadcrumbs_http` to build and run under Flutter 2.5.0 / Dart 2.14.0
Relied on existing tests
> Change the network breadcrumbs packages to require Flutter 2.5.0

- CHANGELOG.md
- packages/bugsnag_flutter/lib/src/model/stackframe.dart
- packages/bugsnag_flutter/test/model/stackframe_test.dart
Don't report a column when `columnNumber`s are not available at runtime. The existing behaviour reports the sentinel `-1` values which create noise in the event reports and make reading the stack traces harder than it needs to be.
New unit test to cover the new behaviour
> Avoid reporting -1 column number

- packages/bugsnag_flutter/lib/src/breadcrumbs/navigation.dart
`BugsnagNavigatorObserver` should change the Event `context` by default to be inline with our over platforms.
Relied on existing tests
> Log navigation context by default

- packages/bugsnag_breadcrumbs_dart_io/README.md
- packages/bugsnag_breadcrumbs_http/README.md
Include `README.md` files for the new network breadcrumbs packages. These packages will appear independently from our main `bugsnag_flutter` package on pub.dev, and should explain what they're used for in their README files.
> Network breadcrumbs README files

- CHANGELOG.md
- packages/bugsnag_flutter/android/build.gradle
Bump bugsnag-android dependency to v5.23.0
Note - this includes a new configuration option that needs to be added to the Unity codebase.
* Added configuration option to control whether internal errors are sent to Bugsnag
[#1701](https://github.com/bugsnag/bugsnag-android/pull/1701)
* Fixed Bugsnag interactions with the Google ANR handler on newer versions of Android
[#1699](https://github.com/bugsnag/bugsnag-android/pull/1699)
* Overwriting & clearing event metadata in the NDK plugin will no longer leave phantom values
[#1700](https://github.com/bugsnag/bugsnag-android/pull/1700)
* Improved `app.inForeground` reporting for NDK errors
[#1690](https://github.com/bugsnag/bugsnag-android/pull/1690)
* Fixed concurrency bug that could be triggered via the React Native plugin …
> Bump bugsnag-android to v5.23.0

- CHANGELOG.md
- packages/bugsnag_flutter/android/build.gradle
* Complex metadata (nested structures such as maps & lists) added in Java/Kotlin is now fully preserved in NDK errors
[#1715](https://github.com/bugsnag/bugsnag-android/pull/1715)
* Configuration.discardClasses now applies to NDK errors
[#1710](https://github.com/bugsnag/bugsnag-android/pull/1710)
> Bump bugsnag-android to v5.24.0

- examples/native/android/app/src/main/AndroidManifest.xml
- examples/native/android/app/src/main/java/com/example/bugsnag/flutter/android/MainActivity.kt
- examples/native/android/app/src/main/res/layout/activity_main.xml
- examples/native/example_flutter/lib/main.dart
- examples/native/ios/BugsnagFlutter/Base.lproj/Main.storyboard
- examples/native/ios/BugsnagFlutter/ViewController.swift
Minor improvements to the native-first Flutter example:
* A Login screen to demonstrate `bugsnag.setUser` and `BugsnagNavigatorObserver`
* Native crashes from the main app screens on Android & iOS
Manually tested
> Add navigation & native errors to the native example

- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
Remove use of `-[BugsnagMetadata deepCopy]` method which is [being removed](https://github.com/bugsnag/bugsnag-cocoa/pull/1444).
Uses `copy` instead of `deepCopy`.
Verified no observable changes via existing tests.
> Use `-[BugsnagMetadata copy]` instead of `-deepCopy`

- examples/native/android/app/src/main/java/com/example/bugsnag/flutter/android/ExampleApp.kt
- examples/native/ios/BugsnagFlutter.xcodeproj/project.pbxproj
- examples/native/ios/BugsnagFlutter/AppDelegate.swift
- examples/native/ios/Podfile
- features/fixtures/app/android/app/src/main/java/com/bugsnag/flutter/test/app/MazeRunnerMethodCallHandler.java
- features/fixtures/app/android/app/src/main/java/com/bugsnag/flutter/test/app/scenario/NativeCrashScenario.java
- features/fixtures/app/android/app/src/main/java/com/bugsnag/flutter/test/app/scenario/NativeProjectPackagesScenario.java
- features/fixtures/app/android/app/src/main/java/com/bugsnag/flutter/test/app/scenario/Scenario.java
- features/fixtures/app/ios/Runner.xcodeproj/project.pbxproj
- features/fixtures/app/ios/Runner/AppDelegate.m
- features/fixtures/app/ios/Runner/Info.plist
- features/fixtures/app/ios/Runner/Scenarios/NativeCrashScenario.m
- features/fixtures/app/ios/Runner/Scenarios/NativeProjectPackagesScenario.m
- features/fixtures/app/ios/Runner/Scenarios/Scenario.h
- features/fixtures/app/ios/Runner/Scenarios/Scenario.m
- features/fixtures/app/lib/channels.dart
- features/fixtures/app/lib/scenarios/native_project_packages_scenario.dart
- features/fixtures/app/lib/scenarios/scenarios.dart
- features/project_packages.feature
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterConfiguration.h
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterConfiguration.m
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
Allow `projectPackages` to be configured when attaching to the Cocoa notifier
Adds `projectPackages` property to `BugsnagFlutterConfiguration` (for Cocoa only) and reads this in the plugin's `attach` method.
Adds new E2E scenario to verify that events have the expected `projectPackages`.
> [PLAT-8727] Allow `projectPackages` to be configured when attaching to Cocoa notifier

- CHANGELOG.md
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/EnumHelper.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/config.dart
- packages/bugsnag_flutter/test/bugsnag_test.dart
Allow Flutter apps to configure Bugsnag's telemetry option.
Adds `BugsnagTelemetryType` enum with a single `internalErrors` member.
Adds optional `telemetry` argument to `bugsnag.start` which defaults to all telemetry.
Updates Android and Cocoa plugins to pass telemetry options through to native layer.
Adds unit test cases to check expected values are passed to channel.
Manually verified expected native values are configured by debugging example app.
> [PLAT-8599] Add `telemetry` option (with `internalErrors`) to `bugsnag.start`

- CHANGELOG.md
- features/breadcrumbs.feature
- features/fixtures/app/lib/scenarios/breadcrumbs_scenario.dart
- packages/bugsnag_flutter/lib/src/model/metadata.dart
Fix 'Unexpected Exception' when encoding metadata containing `List` objects. This was caused by calling `map` in `BugsnagMetadata` without `toList()`, resulting in attempting to encode a `MappedListIterable` (which is not a `List`) when sending the metadata to the native layer.
Added more types (list, number and boolean) to the "breadcrumbs" end to end scenario and assert they are presented as expected.
> Fix JSON error with metadata containing lists

- CHANGELOG.md
- packages/bugsnag_flutter/lib/src/bugsnag_stacktrace.dart
- packages/bugsnag_flutter/test/bugsnag_stacktrace_test.dart
Native stack traces with 'invalid Dart instruction address' frames resulted in `"frameAddress": 0` instead of retaining their message.
Check for the 'invalid Dart instruction address' message and insert a specialised `BugsnagStackframe` in its place.
Manual testing, and new unit tests.
> Handle 'invalid Dart instruction address' native stack frames

- CHANGELOG.md
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/EnumHelper.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
- packages/bugsnag_flutter/lib/src/config.dart
- packages/bugsnag_flutter/test/bugsnag_test.dart
Allow Flutter apps to configure Bugsnag's `usage` telemetry option.
Adds `BugsnagTelemetryType.usage`.
Updates Android and Cocoa plugins to pass `usage` telemetry options through to native layer.
Updates unit test cases to check expected telemetry values are passed to channel.
Manually verified expected native values are configured by debugging example app.
> [PLAT-8719] Add `BugsnagTelemetryType.usage`

- CHANGELOG.md
- features/attach_flutter.feature
- features/fixtures/app/lib/scenarios/attach_bugsnag_scenario.dart
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
Improve hot-reload experience when using `bugsnag.attach` by not throwing an error.
Emit a warning message, instead of throwing an exception when `attach` has already been called.
New end to end scenarios were added to check that additional calls to `attach` do not cause startup failures.
> Additional calls to attach will log a warning

- CHANGELOG.md
- packages/bugsnag_flutter/lib/src/bugsnag_stacktrace.dart
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/test/error_factory_test.dart
Closes #186
If the error has a stack trace but the stacktrace is empty, we should use the fallback stack trace instead of an empty list.
If the stacktrace is empty, we shouldn't crash by calling `.first`.
> Prevent crash with empty stack trace

- CHANGELOG.md
- packages/bugsnag_flutter/lib/src/model/breadcrumbs.dart
- packages/bugsnag_flutter/test/channel_client_test.dart
Closes #198
The metadata is now always sanitised, meaning that all enums are converted to strings.
Test added to ensure that different data types are properly sanitised when passed as metadata.
> Serialize enum metadata

- .github/workflows/update-dependencies.yml
- Gemfile
- Makefile
Adds a github actions workflow to receive messages from upstream repos (bugsnag-android and bugsnag-cocoa) when a new release is made, updating those versions in appropriate places, committing the changes, then pushing and PRing the resulting branch.
Since this is based off of the similar unity pipeline, that represents a test setup for this workflow.  Functions such as those in the makefile have all been run locally.
> Automatically update references to dependencies

- CHANGELOG.md
- packages/bugsnag_flutter/android/build.gradle
- Update bugsnag-android from v5.30.0 to [v5.31.3](https://github.com/bugsnag/bugsnag-android/blob/master/CHANGELOG.md#5313-2023-11-06)
> bump bugsnag android to 3.31.3

- CHANGELOG.md
- packages/bugsnag_breadcrumbs_http/pubspec.yaml
This change allows users to use whatever version of the http lib they like.
Covered by existing tests
> PLAT-11617 change http dep to be less strict

- CHANGELOG.md
- features/fixtures/app/lib/scenarios/null_context_scenario.dart
- features/fixtures/app/lib/scenarios/null_user_scenario.dart
- features/fixtures/app/lib/scenarios/scenarios.dart
- features/null_parameters.feature
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
Fixed an issue related to setting context by navigator observer. In some cases a null is received on Android as a JSONObject.
Added safety checks
Manual testing
> Navigator.pushAndRemoveUntil throws exception in Bugsnag

- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
Prevent getting a null pointer exception if an event is generated before Bugsnag is properly initialized
> Added null checks for client in Android code

- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
This change allows events to be reported after start (instead of attach) is called from a new Flutter context after Flutter has already started
A previously initialized client is reused by the new context (without any changes in its configuration)
> Improved the behaviour on Android when Bugsnag is started multiple times from different contexts

- features/fixtures/app/lib/scenarios/discard_classes_scenario.dart
- features/fixtures/app/lib/scenarios/start_bugsnag_scenario.dart
- packages/bugsnag_flutter/android/build.gradle
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/lib/src/regexp_json.dart
Bump bugsnag-android to the latest version.
The new version of bugsnag-android accepts redactedKeys and discardClasses only as regular expressions. In order to maintain consistency across platforms, the types in bugsnag-flutter were changed to RegExp and they are compiled to regular expressions on both native platforms.
Changed redactedKeys and discardClasses types to RegExp.
Existing E2E tests
> Bump bugsnag-android to v6. Changed redactedKeys and discardClasses types to RegExp

- README.md
The build badge seems to be showing failure as it's the last of any builds in the pipeine. Amended to show `main` builds only.
> docs(readme): amended badge URL to scope to main branch only

- CHANGELOG.md
- features/fixtures/app/pubspec.lock
- packages/bugsnag_flutter/android/src/main/java/com/bugsnag/flutter/BugsnagFlutter.java
- packages/bugsnag_flutter/ios/Classes/BugsnagFlutterPlugin.m
- packages/bugsnag_flutter/ios/bugsnag_flutter.podspec
- packages/bugsnag_flutter/lib/src/client.dart
- packages/bugsnag_flutter/pubspec.yaml
Include the ID of the current trace and span ID in errors when both bugsnag-flutter and bugsnag-flutter-performance are included in an application
BugsnagContextProvider is used to receive traceId and spanId from Flutter Performance and then the values are included in bugsnag-cocoa and bugsnag-android events
Existing E2E tests
> Added trace ID to error events

- CHANGELOG.md
- features/fixtures/app/android/app/build.gradle
- features/fixtures/app/pubspec.lock
- packages/bugsnag_flutter/android/build.gradle
As reported by @hamzaalmahdi
The library is giving errors after the last update of flutter "3.24.0". This is the error "build/bugsnag_flutter/intermediates/merged_res/release/values/values.xml:194: AAPT: error: resource android:attr/lStar not found".
We intially considered upgrading to 34 but decided to go for 31 instead.
Upgraded the compileSdkVersion to 31
Existing E2E Tests
> Upgrade Android compileSdkVersion from 29 to 31

- CHANGELOG.md
- packages/bugsnag_flutter/android/build.gradle
There is an error when the library is used with Android SDK 34 and above. We need to bump the version of bugsnag-android used by bugsnag-flutter to work with Android SDK version 34
> Bumped bugsnag-android dependency version

- features/steps/flutter_steps.rb
Do not use Maze.driver directly, so that any Appium session failures are reported.
Covered by CI.
> Do not use Maze.driver directly

- .buildkite/pipeline.yml
Always upload maze_output.zip as build artifact to assist with debugging of test failures - it gives us an easy reference point for what requests should look like.
Covered by CI.
> Always upload maze_output.zip as build artifact
